ifneq ($(LIBHARVEST_COMP_CHAN),)
override CFLAGS += -DLIBHARVEST_COMP_CHAN=$(LIBHARVEST_COMP_CHAN)
else
$(error Comparator channel must be selected via LIBHARVEST_COMP_CHAN option)
endif

ifneq ($(LIBHARVEST_COMP_REF),)
override CFLAGS += -DLIBHARVEST_COMP_REF=$(LIBHARVEST_COMP_REF)
endif

ifneq ($(LIBHARVEST_COMP_PORT),)
override CFLAGS += \
	-DLIBHARVEST_COMP_PORT=$(firstword $(subst ., ,$(LIBHARVEST_COMP_PORT))) \
	-DLIBHARVEST_COMP_PIN=$(lastword $(subst ., ,$(LIBHARVEST_COMP_PORT)))
else
$(error Port and pin with VDD for comparator must be defined with LIBHARVEST_COMP_PORT, e.g. '9.3')
endif
